<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingHotel.Domain\BookingHotel.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="DTOs\Auth\" />
    <Folder Include="DTOs\Hotel\" />
    <Folder Include="DTOs\Booking\" />
    <Folder Include="DTOs\Room\" />
    <Folder Include="Interfaces\Security\" />
    <Folder Include="Interfaces\Services\" />
    <Folder Include="Interfaces\Repositories\" />
    <Folder Include="Validators\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
