<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingHotel.Application\BookingHotel.Application.csproj" />
    <ProjectReference Include="..\BookingHotel.Domain\BookingHotel.Domain.csproj" />
  </ItemGroup>

</Project>
